### ISSUE TITLE
build is broken w/ new bazel

### ISSUE THREAD

**Issue by jonathantwall** [gautamraj/bazel-java#1]
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/Users/wall/stripe/bazel-java/tools/bazel.rc
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: /Users/wall/stripe/bazel-java/WORKSPACE:1:1: name 'maven_jar' is not defined
ERROR: /Users/wall/stripe/bazel-java/WORKSPACE:2:1: name 'maven_jar' is not defined
ERROR: /Users/wall/stripe/bazel-java/WORKSPACE:3:1: name 'maven_jar' is not defined
ERROR: /Users/wall/stripe/bazel-java/WORKSPACE:4:1: name 'maven_jar' is not defined
ERROR: error loading package '': Encountered error while reading extension file 'tools/build_defs/repo/http.bzl': no such package '@bazel_tools//tools/build_defs/repo': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'tools/build_defs/repo/http.bzl': no such package '@bazel_tools//tools/build_defs/repo': error loading package 'external': Could not load //external package
INFO: Elapsed time: 2.081s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by jonathantwall** [comment]
bazel 2.1.0

**Comment by gautamraj** [comment]
Should work with Bazel 6 now :)

**Comment by jonathantwall** [comment]
go g$
